table Orders
	lineageTag: 26da0f8b-3206-49ad-a61b-fa197b287b32

	measure Umsatz = SUM(Orders[Sales])
		formatString: #,0
		lineageTag: d3c54967-0e44-46c7-859b-6ded6077b37b

	measure Bestellungen = DISTINCTCOUNT(Orders[Order ID])
		formatString: #,0
		lineageTag: 47291e94-1873-43d1-b736-1d9c07eb040d

	measure Positionen = COUNTROWS(Orders)
		formatString: #,0
		lineageTag: 7c42fa38-f319-4065-ae5d-733180d34c04

	measure 'Ø Bestellwert' = DIVIDE([Umsatz], [Bestellungen], 0)
		lineageTag: 589c1094-8afe-46de-ab60-717fdd347239

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Umsatz 2018' = CALCULATE([Umsatz], FILTER(ALL(Orders[Order Date]), YEAR(Orders[Order Date]) = 2018))
		formatString: #,0
		lineageTag: 55b8292e-034a-4486-946d-327ee429d201

	measure 'Umsatz 2017' = CALCULATE([Umsatz], FILTER(ALL(Orders[Order Date]), YEAR(Orders[Order Date]) = 2017))
		formatString: #,0
		lineageTag: 39cb7165-253f-415b-8047-363c3ee59765

	measure 'Bestellungen 2018' = CALCULATE([Bestellungen], FILTER(ALL(Orders[Order Date]), YEAR(Orders[Order Date]) = 2018))
		formatString: #,0
		lineageTag: dba19b82-c635-440c-b83c-cd19dd9b4970

	measure 'Bestellungen 2017' = CALCULATE([Bestellungen], FILTER(ALL(Orders[Order Date]), YEAR(Orders[Order Date]) = 2017))
		formatString: #,0
		lineageTag: ef39f6d6-cf9f-4522-99cc-71d6465899d7

	measure 'Positionen 2018' = CALCULATE([Positionen], FILTER(ALL(Orders[Order Date]), YEAR(Orders[Order Date]) = 2018))
		formatString: #,0
		lineageTag: 3e8b531b-2bc5-4088-8389-06761c98aef4

	measure 'Positionen 2017' = CALCULATE([Positionen], FILTER(ALL(Orders[Order Date]), YEAR(Orders[Order Date]) = 2017))
		formatString: #,0
		lineageTag: 49bb2c56-5f55-4713-9537-3031138eb3e8

	measure 'Bestellwert 2018' = DIVIDE([Umsatz 2018], [Bestellungen 2018], 0)
		formatString: #,0.00
		lineageTag: 1d0779f5-d81b-46a7-a2ff-23a04151da50

	measure 'Bestellwert 2017' = DIVIDE([Umsatz 2017], [Bestellungen 2017], 0)
		formatString: #,0.00
		lineageTag: 806a4a3f-6a32-4f54-adbf-1cf75591c096

	measure 'Umsatz Veränderung' = VAR d = DIVIDE([Umsatz 2018] - [Umsatz 2017], [Umsatz 2017]) RETURN IF(d >= 0, "+", "−") & FORMAT(ABS(d) * 100, "0.0") & " % zum Vorjahr"
		lineageTag: 914306e4-bdd0-4d5e-96bf-886e15fc4403

	measure 'Umsatz Vorjahre' = IF(YEAR(MAX(Orders[Order Date])) < 2018, [Umsatz])
		formatString: #,0
		lineageTag: 180de86c-0295-4438-94ab-18de6dea7c74

	measure 'Umsatz Aktuell' = IF(YEAR(MAX(Orders[Order Date])) = 2018, [Umsatz])
		formatString: #,0
		lineageTag: fe751618-9b7f-40e4-9685-430675379a23

	measure 'Bestellungen Veränderung' = VAR d = DIVIDE([Bestellungen 2018] - [Bestellungen 2017], [Bestellungen 2017]) RETURN IF(d >= 0, "+", "−") & FORMAT(ABS(d) * 100, "0.0") & " % zum Vorjahr"
		lineageTag: d21a9aa0-d283-4144-80dc-2357c392d5d6

	measure 'Bestellungen Vorjahre' = IF(YEAR(MAX(Orders[Order Date])) < 2018, [Bestellungen])
		formatString: #,0
		lineageTag: 3d207e4b-de32-437a-9494-ccea06aff8bf

	measure 'Bestellungen Aktuell' = IF(YEAR(MAX(Orders[Order Date])) = 2018, [Bestellungen])
		formatString: #,0
		lineageTag: 7f8b77db-dbbf-46ac-a964-71d0c03e862a

	measure 'Positionen Veränderung' = VAR d = DIVIDE([Positionen 2018] - [Positionen 2017], [Positionen 2017]) RETURN IF(d >= 0, "+", "−") & FORMAT(ABS(d) * 100, "0.0") & " % zum Vorjahr"
		lineageTag: 02f3e07e-f017-4329-a9ac-0e0b7b84ffa7

	measure 'Positionen Vorjahre' = IF(YEAR(MAX(Orders[Order Date])) < 2018, [Positionen])
		formatString: #,0
		lineageTag: 74d7a029-6408-42fb-93b5-a260f1abe19d

	measure 'Positionen Aktuell' = IF(YEAR(MAX(Orders[Order Date])) = 2018, [Positionen])
		formatString: #,0
		lineageTag: dce2f3a9-3fc5-41c9-9720-8ae263db43e1

	measure 'Bestellwert Veränderung' = VAR d = DIVIDE([Bestellwert 2018] - [Bestellwert 2017], [Bestellwert 2017]) RETURN IF(d >= 0, "+", "−") & FORMAT(ABS(d) * 100, "0.0") & " % zum Vorjahr"
		lineageTag: 646b75dd-226e-4b3b-8179-24f0fb67844e

	measure 'Bestellwert Vorjahre' = IF(YEAR(MAX(Orders[Order Date])) < 2018, [Ø Bestellwert])
		formatString: #,0.00
		lineageTag: dc3c514a-b58e-4ce6-b906-dbd93ab0b778

	measure 'Bestellwert Aktuell' = IF(YEAR(MAX(Orders[Order Date])) = 2018, [Ø Bestellwert])
		formatString: #,0.00
		lineageTag: bf781684-c54d-4e1e-9ff7-a9106f1c43b0

	measure 'Letzter Monat' = IF(MAX(Orders[Order Date]) >= DATE(2018, 12, 1), [Umsatz])
		formatString: #,0
		lineageTag: 6561ecf0-c8cc-4720-b008-1d2eb00e65f8

	measure Saisonpunkte = IF(MONTH(MAX(Orders[Order Date])) >= 11 && MAX(Orders[Order Date]) < DATE(2018, 12, 1), [Umsatz])
		formatString: #,0
		lineageTag: 2027234b-4782-473f-915f-5475cf94b9e7

	measure Zeitraum = VAR mn = MIN(Orders[Jahr]) VAR mx = MAX(Orders[Jahr]) RETURN IF(mn = mx, FORMAT(mn, "0"), FORMAT(mn, "0") & "–" & FORMAT(mx, "0"))
		lineageTag: 21edbe1b-3668-41b5-b2ba-455b303e916b

	measure 'Untertitel Umsatz' = "Umsatz in US-Dollar, " & [Zeitraum]
		lineageTag: e71e5eba-8659-4359-9260-e78036998f42

	measure 'Untertitel Sub-Kategorie' = "Umsatz in US-Dollar je Sub-Kategorie, " & [Zeitraum]
		lineageTag: d4167611-b793-44ad-ba76-263c8f794611

	measure 'Untertitel Monate' = "Umsatz je Monat in US-Dollar, " & [Zeitraum]
		lineageTag: 6ce8311d-0871-4cfa-b775-38eb3b4e25b2

	column 'Row ID'
		dataType: string
		lineageTag: 62b9a4b0-3bdd-4f41-904a-159fc737fc27
		summarizeBy: none
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 6a4993e1-8f7b-4087-a62d-76abb7c76420
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: #,0.00
		lineageTag: c933365b-9dbb-4ac4-abe5-2455b18981cf
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 301fe429-daf0-4e4a-b849-e362ce9861df
			defaultHierarchy: LocalDateTable_bf17564c-115b-4606-ab4d-7af6c2687a5d.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f3789213-e718-4824-ad4e-b1c4bea5fc03
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 11397fd9-9247-4f8c-b8b6-906fb0574e7d
			defaultHierarchy: LocalDateTable_37812e14-f286-460b-930e-fb58c2b0a72b.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 4d12c9a6-157e-42da-8146-8b6e4d91a9a0
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 087e5f6d-f082-4020-ab4c-1a30b38d5674
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: a1bfe2b2-78a8-42fa-a9c9-4a103f03171c
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 85e2dcdd-59d7-49ee-8e16-cf115fae296d
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 2148f165-3985-44e1-b997-baace8993213
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: b26d28cb-7580-49bf-8705-230157402493
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: b2f50bea-fe71-49e4-a9a6-9a4f9560a52f
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: f856d4f5-bbdd-49b1-963d-e48b665ea911
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: a48e33b8-56a6-4dfd-a457-1be331b2f47c
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 6fdbf083-5e70-47ca-b8e9-19dd82ecbc23
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 81a6a732-2bba-48ed-be4a-0b07a33dd328
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 44af7d4f-4e9f-4802-9355-5a9f4302e9a7
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 486f3759-13b9-4014-aa16-efab126d375d
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: 0
		lineageTag: df0c440b-b4e5-447e-8e94-07d74a64484a
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Jahr = YEAR(Orders[Order Date])
		formatString: 0
		lineageTag: 68e58f56-73a3-44f5-a4c7-ff7eff2a1c10
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Jahr kurz' = "'" & RIGHT(FORMAT(Orders[Jahr], "0"), 2)
		lineageTag: c69fa104-f596-4ede-b1da-f00266d2daa2
		summarizeBy: none
		sortByColumn: Jahr

		annotation SummarizationSetBy = Automatic

	partition Orders = m
		mode: import
		source =
				let
				  Quelle = Csv.Document(File.Contents("C:\BINT\train.csv"), [Delimiter = ",", Columns = 18, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Höher gestufte Header" = Table.PromoteHeaders(Quelle, [PromoteAllScalars = true]),
				  #"Geänderter Typ mit Gebietsschema" = Table.TransformColumnTypes(#"Höher gestufte Header", {{"Sales", type number}}, "en-US"),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Geänderter Typ mit Gebietsschema",{{"Order Date", type date}, {"Ship Date", type date}})
				in
				  #"Geänderter Typ"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

