table Orders
	lineageTag: 26da0f8b-3206-49ad-a61b-fa197b287b32

	measure Umsatz = SUM(Orders[Sales])
		formatString: #,0
		lineageTag: d3c54967-0e44-46c7-859b-6ded6077b37b

	measure Bestellungen = DISTINCTCOUNT(Orders[Order ID])
		formatString: #,0
		lineageTag: 47291e94-1873-43d1-b736-1d9c07eb040d

	measure Positionen = COUNTROWS(Orders)
		formatString: #,0
		lineageTag: 7c42fa38-f319-4065-ae5d-733180d34c04

	measure 'Ø Bestellwert' = DIVIDE([Umsatz], [Bestellungen], 0)
		lineageTag: 589c1094-8afe-46de-ab60-717fdd347239

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Umsatz Veränderung' = VAR a = [Umsatz Bezugsjahr] VAR v = [Umsatz Vorjahr] VAR d = DIVIDE(a - v, v) RETURN IF(ISBLANK(v) || v = 0, "kein Vorjahr im Datensatz", IF(d >= 0, "+", "−") & FORMAT(ABS(d) * 100, "0.0") & " % zum Vorjahr")
		lineageTag: 7f941950-664e-4a90-9ba3-dbda293a1436

	measure 'Umsatz Vorjahre' = VAR j = [Bezugsjahr] VAR y = MAX(Jahre[Jahr]) RETURN IF(y <> j, CALCULATE([Umsatz], REMOVEFILTERS(Orders[Jahr]), Orders[Jahr] = y))
		formatString: #,0
		lineageTag: 364d2db5-0451-44a7-8b70-4264f9db65b3

	measure 'Umsatz Aktuell' = VAR j = [Bezugsjahr] VAR y = MAX(Jahre[Jahr]) RETURN IF(y = j, CALCULATE([Umsatz], REMOVEFILTERS(Orders[Jahr]), Orders[Jahr] = y))
		formatString: #,0
		lineageTag: 325ba7ad-8c81-4d96-aae3-7adc5db122e2

	measure 'Bestellungen Veränderung' = VAR a = [Bestellungen Bezugsjahr] VAR v = [Bestellungen Vorjahr] VAR d = DIVIDE(a - v, v) RETURN IF(ISBLANK(v) || v = 0, "kein Vorjahr im Datensatz", IF(d >= 0, "+", "−") & FORMAT(ABS(d) * 100, "0.0") & " % zum Vorjahr")
		lineageTag: 1ff95a45-f36f-4908-8e02-fc7050d1ae63

	measure 'Bestellungen Vorjahre' = VAR j = [Bezugsjahr] VAR y = MAX(Jahre[Jahr]) RETURN IF(y <> j, CALCULATE([Bestellungen], REMOVEFILTERS(Orders[Jahr]), Orders[Jahr] = y))
		formatString: #,0
		lineageTag: 6fc2befc-a08a-4c3b-bbdd-c4d6f1dc61f1

	measure 'Bestellungen Aktuell' = VAR j = [Bezugsjahr] VAR y = MAX(Jahre[Jahr]) RETURN IF(y = j, CALCULATE([Bestellungen], REMOVEFILTERS(Orders[Jahr]), Orders[Jahr] = y))
		formatString: #,0
		lineageTag: f0d87c12-cc6f-421b-acad-5ff14b3de475

	measure 'Positionen Veränderung' = VAR a = [Positionen Bezugsjahr] VAR v = [Positionen Vorjahr] VAR d = DIVIDE(a - v, v) RETURN IF(ISBLANK(v) || v = 0, "kein Vorjahr im Datensatz", IF(d >= 0, "+", "−") & FORMAT(ABS(d) * 100, "0.0") & " % zum Vorjahr")
		lineageTag: d956f68b-19c6-46af-8a28-795b40832bcd

	measure 'Positionen Vorjahre' = VAR j = [Bezugsjahr] VAR y = MAX(Jahre[Jahr]) RETURN IF(y <> j, CALCULATE([Positionen], REMOVEFILTERS(Orders[Jahr]), Orders[Jahr] = y))
		formatString: #,0
		lineageTag: 369742d3-22cd-485d-88b1-49551016eb71

	measure 'Positionen Aktuell' = VAR j = [Bezugsjahr] VAR y = MAX(Jahre[Jahr]) RETURN IF(y = j, CALCULATE([Positionen], REMOVEFILTERS(Orders[Jahr]), Orders[Jahr] = y))
		formatString: #,0
		lineageTag: cd1c7c09-f8d4-4d1d-9fa3-5127f11c3956

	measure 'Bestellwert Veränderung' = VAR a = [Bestellwert Bezugsjahr] VAR v = [Bestellwert Vorjahr] VAR d = DIVIDE(a - v, v) RETURN IF(ISBLANK(v) || v = 0, "kein Vorjahr im Datensatz", IF(d >= 0, "+", "−") & FORMAT(ABS(d) * 100, "0.0") & " % zum Vorjahr")
		lineageTag: f4116f2c-3e33-42aa-9fe7-81b5f26c1a8d

	measure 'Bestellwert Vorjahre' = VAR j = [Bezugsjahr] VAR y = MAX(Jahre[Jahr]) RETURN IF(y <> j, CALCULATE([Ø Bestellwert], REMOVEFILTERS(Orders[Jahr]), Orders[Jahr] = y))
		formatString: #,0.00
		lineageTag: 444f9e2a-7ddf-4578-9dab-d4d74910a26a

	measure 'Bestellwert Aktuell' = VAR j = [Bezugsjahr] VAR y = MAX(Jahre[Jahr]) RETURN IF(y = j, CALCULATE([Ø Bestellwert], REMOVEFILTERS(Orders[Jahr]), Orders[Jahr] = y))
		formatString: #,0.00
		lineageTag: ee200234-fec4-46db-ab7d-9045aa89f3b1

	measure 'Letzter Monat' = IF(MAX(Orders[Order Date]) >= DATE(2018, 12, 1), [Umsatz])
		formatString: #,0
		lineageTag: 6561ecf0-c8cc-4720-b008-1d2eb00e65f8

	measure Saisonpunkte = IF(MONTH(MAX(Orders[Order Date])) >= 11 && MAX(Orders[Order Date]) < DATE(2018, 12, 1), [Umsatz])
		formatString: #,0
		lineageTag: 2027234b-4782-473f-915f-5475cf94b9e7

	measure Zeitraum = VAR mn = MIN(Orders[Jahr]) VAR mx = MAX(Orders[Jahr]) RETURN IF(mn = mx, FORMAT(mn, "0"), FORMAT(mn, "0") & "–" & FORMAT(mx, "0"))
		lineageTag: 21edbe1b-3668-41b5-b2ba-455b303e916b

	measure 'Untertitel Umsatz' = "Umsatz in US-Dollar, " & [Zeitraum]
		lineageTag: e71e5eba-8659-4359-9260-e78036998f42

	measure 'Untertitel Sub-Kategorie' = "Umsatz in US-Dollar je Sub-Kategorie, " & [Zeitraum]
		lineageTag: d4167611-b793-44ad-ba76-263c8f794611

	measure 'Untertitel Monate' = "Umsatz je Monat in US-Dollar, " & [Zeitraum]
		lineageTag: 6ce8311d-0871-4cfa-b775-38eb3b4e25b2

	measure Bezugsjahr = MAX(Orders[Jahr])
		formatString: 0
		lineageTag: d02a7783-ce87-486a-bfed-322318468ed9

	measure 'Umsatz Bezugsjahr' = VAR j = [Bezugsjahr] RETURN CALCULATE([Umsatz], FILTER(ALL(Orders[Jahr]), Orders[Jahr] = j))
		formatString: #,0
		lineageTag: 58467f08-de96-46cd-b8f2-7cddc8533fe3

	measure 'Umsatz Vorjahr' = VAR j = [Bezugsjahr] RETURN CALCULATE([Umsatz], FILTER(ALL(Orders[Jahr]), Orders[Jahr] = j - 1))
		formatString: #,0
		lineageTag: 5c1484f3-f7b7-44ce-814a-119dc365ccd7

	measure 'Umsatz Farbe' = IF(ISBLANK([Umsatz Vorjahr]) || [Umsatz Bezugsjahr] >= [Umsatz Vorjahr], "#1E3A8A", "#B23B1E")
		lineageTag: f9b20c06-61b6-457c-9052-31a380b8c4d8

	measure 'Umsatz Titel' = "UMSATZ " & [Bezugsjahr]
		lineageTag: cc12fe16-aebf-4d49-be46-491718224b29

	measure 'Bestellungen Bezugsjahr' = VAR j = [Bezugsjahr] RETURN CALCULATE([Bestellungen], FILTER(ALL(Orders[Jahr]), Orders[Jahr] = j))
		formatString: #,0
		lineageTag: f02c96f5-722b-465c-9a39-f30daeddc1da

	measure 'Bestellungen Vorjahr' = VAR j = [Bezugsjahr] RETURN CALCULATE([Bestellungen], FILTER(ALL(Orders[Jahr]), Orders[Jahr] = j - 1))
		formatString: #,0
		lineageTag: e9b19e87-9a75-446d-ae3c-a2bc5ebcc511

	measure 'Bestellungen Farbe' = IF(ISBLANK([Bestellungen Vorjahr]) || [Bestellungen Bezugsjahr] >= [Bestellungen Vorjahr], "#1E3A8A", "#B23B1E")
		lineageTag: e7180128-e995-4d6f-8ed9-e2436d000a07

	measure 'Bestellungen Titel' = "BESTELLUNGEN " & [Bezugsjahr]
		lineageTag: 4ec420e1-c6dd-4d1c-b385-840f5360da63

	measure 'Positionen Bezugsjahr' = VAR j = [Bezugsjahr] RETURN CALCULATE([Positionen], FILTER(ALL(Orders[Jahr]), Orders[Jahr] = j))
		formatString: #,0
		lineageTag: e0334339-f480-4f4c-9984-2357e126b40c

	measure 'Positionen Vorjahr' = VAR j = [Bezugsjahr] RETURN CALCULATE([Positionen], FILTER(ALL(Orders[Jahr]), Orders[Jahr] = j - 1))
		formatString: #,0
		lineageTag: 22e8b688-33f8-4e8e-9881-ea6afe7fc232

	measure 'Positionen Farbe' = IF(ISBLANK([Positionen Vorjahr]) || [Positionen Bezugsjahr] >= [Positionen Vorjahr], "#1E3A8A", "#B23B1E")
		lineageTag: aa791d82-6837-449c-aeaf-858616b2fc86

	measure 'Positionen Titel' = "POSITIONEN " & [Bezugsjahr]
		lineageTag: dba78864-1508-4496-9f1a-a0a093af2478

	measure 'Bestellwert Bezugsjahr' = VAR j = [Bezugsjahr] RETURN CALCULATE([Ø Bestellwert], FILTER(ALL(Orders[Jahr]), Orders[Jahr] = j))
		formatString: #,0.00
		lineageTag: bee2005c-bd6b-4bd9-a1b7-8fa0f5ad1167

	measure 'Bestellwert Vorjahr' = VAR j = [Bezugsjahr] RETURN CALCULATE([Ø Bestellwert], FILTER(ALL(Orders[Jahr]), Orders[Jahr] = j - 1))
		formatString: #,0.00
		lineageTag: baa7daab-8faa-4355-b2b4-353b4640a137

	measure 'Bestellwert Farbe' = IF(ISBLANK([Bestellwert Vorjahr]) || [Bestellwert Bezugsjahr] >= [Bestellwert Vorjahr], "#1E3A8A", "#B23B1E")
		lineageTag: 39181b6b-b591-402c-9428-77c8e25f76f2

	measure 'Bestellwert Titel' = "Ø BESTELLWERT " & [Bezugsjahr]
		lineageTag: a0921c3f-1c03-403d-8a21-bb2087397f3c

	column 'Row ID'
		dataType: string
		lineageTag: 62b9a4b0-3bdd-4f41-904a-159fc737fc27
		summarizeBy: none
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 6a4993e1-8f7b-4087-a62d-76abb7c76420
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: #,0.00
		lineageTag: c933365b-9dbb-4ac4-abe5-2455b18981cf
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 301fe429-daf0-4e4a-b849-e362ce9861df
			defaultHierarchy: LocalDateTable_bf17564c-115b-4606-ab4d-7af6c2687a5d.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f3789213-e718-4824-ad4e-b1c4bea5fc03
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 11397fd9-9247-4f8c-b8b6-906fb0574e7d
			defaultHierarchy: LocalDateTable_37812e14-f286-460b-930e-fb58c2b0a72b.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 4d12c9a6-157e-42da-8146-8b6e4d91a9a0
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 087e5f6d-f082-4020-ab4c-1a30b38d5674
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: a1bfe2b2-78a8-42fa-a9c9-4a103f03171c
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 85e2dcdd-59d7-49ee-8e16-cf115fae296d
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 2148f165-3985-44e1-b997-baace8993213
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: b26d28cb-7580-49bf-8705-230157402493
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: b2f50bea-fe71-49e4-a9a6-9a4f9560a52f
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: f856d4f5-bbdd-49b1-963d-e48b665ea911
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: a48e33b8-56a6-4dfd-a457-1be331b2f47c
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 6fdbf083-5e70-47ca-b8e9-19dd82ecbc23
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 81a6a732-2bba-48ed-be4a-0b07a33dd328
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 44af7d4f-4e9f-4802-9355-5a9f4302e9a7
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 486f3759-13b9-4014-aa16-efab126d375d
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: 0
		lineageTag: df0c440b-b4e5-447e-8e94-07d74a64484a
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Jahr = YEAR(Orders[Order Date])
		formatString: 0
		lineageTag: 68e58f56-73a3-44f5-a4c7-ff7eff2a1c10
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Jahr kurz' = "'" & RIGHT(FORMAT(Orders[Jahr], "0"), 2)
		lineageTag: c69fa104-f596-4ede-b1da-f00266d2daa2
		summarizeBy: none
		sortByColumn: Jahr

		annotation SummarizationSetBy = Automatic

	partition Orders = m
		mode: import
		source =
				let
				  Quelle = Csv.Document(File.Contents("C:\BINT\train.csv"), [Delimiter = ",", Columns = 18, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Höher gestufte Header" = Table.PromoteHeaders(Quelle, [PromoteAllScalars = true]),
				  #"Geänderter Typ mit Gebietsschema" = Table.TransformColumnTypes(#"Höher gestufte Header", {{"Sales", type number}}, "en-US"),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Geänderter Typ mit Gebietsschema",{{"Order Date", type date}, {"Ship Date", type date}})
				in
				  #"Geänderter Typ"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

